Refactored Code
aniruddh622003/major-1 pull request #22
Opened 2023-09-22 18:14 UTC by rishimadan14

2023-09-22 22:07 UTC, aniruddh622003 requested changes

2023-09-22 22:07 UTC, aniruddh622003 commented on api/index.py
> -
I think you removed the functionality of saving file in 'data.csv'

2023-09-23 06:33 UTC, rishimadan14 commented
sharing the changes for saving filename as data.csv every time a new file hits.
    # in order to track harmful content
    filename = secure_filename("data.csv")
    file_path = os.path.join(app.config['Upload_Folder'], filename)

2023-09-23 06:35 UTC, rishimadan14 commented
changes also pulled

2023-09-23 16:16 UTC, aniruddh622003 commented
changes push to krde bhai

2023-09-25 22:18 UTC, aniruddh622003 approved these changes

2023-09-25 22:19 UTC, merged